# Generated by Django 3.2 on 2021-08-03 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstaAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('dateCreated', models.DateField(auto_now_add=True)),
                ('hashtags', models.JSONField(default=list, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InstaUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('interacted', models.BooleanField(default=False)),
                ('dateCollected', models.DateField(auto_now_add=True)),
                ('instaaccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instaaccount.instaaccount')),
            ],
        ),
        migrations.CreateModel(
            name='InstaStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followers', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('instaaccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instaaccount.instaaccount')),
            ],
        ),
    ]
