# Generated by Django 3.2 on 2021-06-30 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstaUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('interacted', models.BooleanField(default=False)),
                ('dateCollected', models.DateField(auto_now_add=True)),
                ('dateInteracted', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InstaAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('followers', models.IntegerField()),
                ('dateCreated', models.DateField(auto_now_add=True)),
                ('hashtags', models.JSONField(default=list)),
                ('instaUsers', models.ManyToManyField(to='instaaccount.InstaUser')),
            ],
        ),
    ]
