# Generated by Django 3.2 on 2021-08-03 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaaccount', '0002_instaaccount_kaminousername'),
    ]

    operations = [
        migrations.AddField(
            model_name='instaaccount',
            name='slug',
            field=models.SlugField(blank=True, max_length=150),
        ),
    ]
