# Generated by Django 3.2 on 2021-07-01 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instaaccount', '0002_instaaccount_kaminousername'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instaaccount',
            name='followers',
        ),
        migrations.CreateModel(
            name='InstaStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followers', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('instaaccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instaaccount.instaaccount')),
            ],
        ),
    ]
