# Generated by Django 3.2 on 2021-07-01 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instaaccount', '0004_remove_instauser_dateinteracted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instaaccount',
            name='instaUsers',
        ),
        migrations.AddField(
            model_name='instauser',
            name='instaaccount',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='instaaccount.instaaccount'),
            preserve_default=False,
        ),
    ]
