# Generated by Django 3.2 on 2021-07-01 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instaaccount', '0005_auto_20210701_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instaaccount',
            name='kaminousername',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
