# Generated by Django 3.2 on 2021-07-01 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaaccount', '0006_alter_instaaccount_kaminousername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instaaccount',
            name='hashtags',
            field=models.JSONField(default=list, null=True),
        ),
    ]
