# Generated by Django 3.2 on 2021-06-27 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='hashtags',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='account',
            name='instaUsers',
            field=models.JSONField(default=list),
        ),
    ]
