# Generated by Django 3.2 on 2021-06-27 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210627_2205'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstaUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('interacted', models.BooleanField(default=False)),
                ('dateCollected', models.DateField(auto_now_add=True)),
                ('dateInteracted', models.DateField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='account',
            name='instaUsers',
        ),
        migrations.AddField(
            model_name='account',
            name='instaUsers',
            field=models.ManyToManyField(to='api.InstaUser'),
        ),
    ]
