# Generated by Django 3.2 on 2021-06-29 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210627_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instauser',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
