# Generated by Django 3.2 on 2021-06-29 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_account_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='instaUsers',
            field=models.ManyToManyField(null=True, to='api.InstaUser'),
        ),
    ]
