# Generated by Django 3.2 on 2021-06-29 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_account_instausers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='instaUsers',
            field=models.ManyToManyField(to='api.InstaUser'),
        ),
    ]
