# Generated by Django 3.2 on 2021-06-30 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_account_instaaccount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InstaAccount',
        ),
        migrations.DeleteModel(
            name='InstaUser',
        ),
    ]
